config/routes.rb
  Rails.application.routes.draw do

  devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  ActiveAdmin.routes(self)
  root_path = 'home#index'

  get '/users/auth/:provider' => 'omniauth_sessions#create', as: 'omniauth_authorize'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    devise_scope :user do
      get 'omniauth/:provider' => 'omniauth_callbacks#localized', as: :localized_omniauth
    end

      devise_for :users, skip: :omniauth_callbacks


      get 'users/change_password'
      put 'users/save_password' => 'users#save_password'

      resources :pictures do
        get 'refresh', on: :collection
        get 'copy', on: :member
      end

      resources :looks do
         collection do
           get 'autocomplete_user_email'
           get 'shared'
         end
         member do
            post 'add_pictures'
            get 'approve_shared'
            get 'remove_shared'
         end
     end

      resources :categories do
        get 'available_pictures', on: :member
        post 'add_pictures', on: :member
      end

      resources :user_settings do
        collection do
          get 'change'
          put 'save'
        end
      end

      get 'api_keys/access_token' => 'api_keys#recreate_access_token'

      get 'users/profile', as: 'user_root'
      root to: root_path

      mount External::ApiVersion1 => '/'

      match '*path', :to => 'application#path_not_found', via: [:get, :post]
  end

end

app/models/look.rb
class Look < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :user
  has_many :look_pictures, dependent: :destroy
  has_many :pictures, -> { uniq }, :through => :look_pictures
  belongs_to :screen, :class_name => "Picture", :foreign_key => "picture_id"

  has_many :user_looks, dependent: :destroy
  has_many :shared_users, through: :user_looks, source: :user

  attr_accessor :user_email, :shared_users_ids
  accepts_nested_attributes_for :look_pictures, :allow_destroy => true
  accepts_nested_attributes_for :screen
  accepts_nested_attributes_for :user_looks, :allow_destroy => true

  validates :name, presence: true
  validates_length_of :name, :minimum => 3, :if => proc{|p| p.name.present?}
  validates :user_id, presence: true

  scope :with_approved, ->(u_id) { includes(:user_looks).where(user_looks: {user_id: u_id}) }

  POSITION_PARAMS = [:top, :left, :width, :height]

  after_create do |look|
    if look.screen.present? && look.user.user_setting.try(:look_screen_category_id)
      look.screen.categories << look.user.user_setting.look_screen_category
    end
  end

  def decode_screen_image(encoded_file = nil)
    return unless encoded_file.present?
    decoded_file = Base64.decode64(encoded_file['data:image/png;base64,'.length .. -1])
    screen_image = Tempfile.new(["image-#{self.user.id}-#{DateTime.now.to_i}",'.jpg'])
    screen_image.binmode  # set to binary mode to avoid UTF-8 conversion errors
    screen_image.write decoded_file
    self.screen.image = screen_image
  end

  before_save :set_position_params

  private

  def set_position_params
    look_pictures.sort_by(&:position_order_for_sort).each_with_index do |lp, index|
      params = POSITION_PARAMS.map do |n|
        position_value = lp.send(n.to_sym)
        next if position_value.nil?
        [n.to_sym, position_value.to_i]
      end
      lp.position_params.merge!(params.to_h.merge({order: index + 1}))
    end
  end

end

app/controllers/looks_controller.rb
class LooksController < ApplicationController

  before_action :set_look, only: [:new, :show, :edit, :update, :destroy, :add_pictures]
  before_action :set_look_screen, only: [:new, :edit]
  before_action :add_extra_pictures_to_canvas, only: :add_pictures, if: proc{ params[:look].present? }
  before_action :reset_look_pictures, only: [:new, :edit]

  set_tab :looks_list, :only => %w(index)
  set_tab :looks_shared, :only => %w(shared)

  autocomplete :user, :email, :extra_data => [:id]

  include SearchFilter

  def get_autocomplete_items(parameters)
    #items = super(parameters) #rails4-autocomplete
    #items = active_record_get_autocomplete_items(parameters) #rails-jquery-autocomplete
    active_record_get_autocomplete_items(parameters).select{|user| !user.eql?(current_user)}.presence || [OpenStruct.new(id: '', parameters[:method].to_s => 'nothing found')]
  end

  def index
    @search, @looks = filtered_looks(current_user.looks, params)
  end

  def shared
    @search, @looks = filtered_looks(current_user.shared_looks.with_approved(current_user.id), params)
    render "index", locals: {is_shared_looks: true}
  end

  def approve_shared
    user_look = UserLook.find_user_look(current_user.id, params[:id])
    if user_look && user_look.update(is_approved: true)
      redirect_to shared_looks_path, notice: 'Shared look was successfully approved.'
    else
      redirect_to shared_looks_path, notice: 'You can\'t approve this sharing.'
    end
  end

  def remove_shared
    user_look = UserLook.find_user_look(current_user.id, params[:id])
    if user_look.delete
      redirect_to shared_looks_path, notice: 'Shared look was declined. It\'s owner was notified'
    else
      redirect_to shared_looks_path, notice: 'You can\'t decline this sharing.'
    end
  end

  def create
    @look = current_user.looks.new(look_params).decorate
    if @look.save
      @look.decode_screen_image(look_params[:screen_attributes][:image_encoded])
      @look.save if @look.screen.changed?
      redirect_to looks_path, notice: 'Look was successfully created.'
    else
      render :new
    end
  end

  def update
    @look.decode_screen_image(look_params[:screen_attributes][:image_encoded])
    if @look.update(look_params)
      redirect_to looks_path, notice: 'Look was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @look.destroy
    redirect_to looks_path, notice: 'Look was successfully destroyed.'
  end

  def add_pictures
    render 'extra_pictures'
  end

  private

  def set_look
    @look = ['0', nil].include?(params[:id]) ? current_user.looks.new.decorate : current_user.looks.find(params[:id]).decorate
  end

  def set_look_screen
    @look.screen = current_user.pictures.new if @look.present? && @look.screen.blank?
  end

  def reset_look_pictures
    cookies[:look_pictures_ids] = @look.pictures.ids.join(',')
    session.delete(:look_pictures_search)
  end

  def add_extra_pictures_to_canvas
    extra_pictures = current_user.pictures.where("id in (?)", look_params[:picture_ids])
    all_extra_pictures_ids = cookies[:look_pictures_ids].split(",") + extra_pictures.ids
    cookies[:look_pictures_ids] = all_extra_pictures_ids.join(',')
    @extra_look_pictures = extra_pictures.map{|p| p.look_pictures.build }
  end

  def look_params
    params.require(:look).permit(:name, :description, picture_ids: [], look_pictures_attributes: [:top, :left, :width, :height, :order, :picture_id, :id, :_destroy],
            screen_attributes: [:id, :title, :user_id, :image_encoded], user_looks_attributes: [:id, :user_id, :_destroy])
  end

end

app/helpers/looks_helper.rb
module LooksHelper

  def look_id_for_pictures_search
    params[:look_id] || 0
  end

end

app/views/looks/_filters.html.haml
.filters
  = search_form_for @search, enforce_utf8: false, html: { class: "form-inline" } do |f|
    %label Sort by:
    = sort_link @search, :name, 'name', {}, { class: '' }
    = sort_link @search, :created_at, 'date', {}, { class: '' }
    .form-group
      = f.text_field :name_cont, :class =>"search-query form-control", "placeholder" => 'Type name or part..'
    = f.submit 'Search', :class => "btn btn-grey"
    = link_to is_shared_looks ? shared_looks_path : looks_path, class: "btn" do
      Refresh
      %i.glyphicon.glyphicon-refresh

app/views/looks/_form.html.haml
= form_for(@look, authenticity_token: true, html: {class: 'lookbox-form', multipart: true, id: "look-save-form"}) do |f|
  = render 'shared/error_message', entity: @look

  .look-toggler.form-inline
    .row
      .col-sm-12
        .div{class: "collapse in", id: "look_options"}
          .form-group
            = f.label :name, class: "control-label"
            = f.text_field :name, class: "form-control"

          .form-group
            = f.label :description, class: "control-label"
            = f.text_area :description, class: "form-control"

          .form-group
            = f.label "Shared with", class: "control-label"
            = react_component 'LookUsers', {potential_users: "#{ current_user.potential_shared_users }", shared_users: "#{ @look.user_looks.to_json(only: :id, include: {user: { only: [:id, :email, :name]} })}"}, class: "inline-block"
            = hidden_field_tag "shared-users-count", @look.shared_users.count

    .row
      .col-sm-9
        = react_component 'LookPictureScreen'
      .col-sm-3
        .div{class: "btn btn-primary btn-look-options", type: "button", :'data-toggle' => "collapse", :'data-target' => "#look_options", :'aria-expanded' => "true", :'aria-controler' => "look_options"}
          Hide params...
        = link_to pictures_path(look_id: @look.id || 0, restore_page: 1), class: "btn btn-add-new", remote: true do
          %i.glyphicon.glyphicon-plus
          Add Picture

  = f.fields_for :screen do |fs|
    = fs.hidden_field :title, id: "preview-image-title", value: "#{@look.name} screen"
    = fs.hidden_field :user_id
    = fs.hidden_field :id

  .look-canvas-container
    #look-canvas.pictures-list
      = react_component 'LookPictures', { look_pictures: @look.look_pictures.to_json(include: :picture) }

%div{id: "pictures-modal", class: "modal fade", tabindex: "-1", role: "dialog", :'aria-labelledby' => "modal-label " }
%div{id: "picture-modal-form", class: "modal fade", tabindex: "-1", role: "dialog", :"aria-labelledby" => "modal-label "}

app/views/looks/_looks_list.html.haml
= render "filters", is_shared_looks: is_shared_looks
.pictures-list.clearfix
  - @looks.each do |look|
    .look-info
      %div{class: "modal fade", id: "look-modal-#{look.id}", tabindex: "-1", role: "dialog", :"aria-labelledby" => "modal-label "}
        = render 'looks/modals/show', look: look
      .look-name.text-short
        = look.name
      .image-block.look-block
        = link_to image_tag(look.preview_image, alt: 'No image', class: "image-space"), "#", data: {toggle: "modal", target: "#look-modal-#{look.id}"}
      - if is_shared_looks
        .look-name
          Shared from:
          = look.user.email
        .shared-looks-actions
          = link_to "Approve", approve_shared_look_path(look), class: 'btn btn-primary' unless look.user_looks[0].is_approved
          = link_to "Decline", remove_shared_look_path(look), method: :get, class: 'btn btn-primary', data: { confirm: "You're going to decline watching this look", :"confirm-success-label" => 'Decline' }

- no_looks = is_shared_looks ? "No one shared with you look has been found." : "No one look has been added yet. Press 'New look' to add the first one."
= current_user.looks.any? ? "No results found. Refresh to view all items." : no_looks unless @looks.any?

= paginate @looks

app/views/looks/_pictures_list.html.haml
- look_pictures.each.with_index(current_child_index - 1) do |look_picture, index|
  = f.fields_for :look_pictures, look_picture, child_index: index do |f_lp|
    %div{id: "look-picture-#{look_picture.picture.id}-position"}
      = f_lp.hidden_field :id
      = f_lp.hidden_field :picture_id
      = f_lp.hidden_field :_destroy
      = f_lp.hidden_field :position_top, { value: look_picture.position_params[:top] }
      = f_lp.hidden_field :position_left, { value: look_picture.position_params[:left] }
      = f_lp.hidden_field :position_order, { value: look_picture.order_number }

  .draggable.ui-widget-content.look-picture-block{id: "look-picture-#{look_picture.picture.id}", style: "top: #{look_picture.position_params[:top]}px; left: #{look_picture.position_params[:left]}px; z-index: #{look_picture.order_number} " }
    = image_tag look_picture.picture.image.url, class: "resizable image-space", :'data-toggle' => "tooltip", title: "", style: "width:auto; height: 200px;"
    .picture-action
      .remove-look-picture-btn
        %span.glyphicon.glyphicon-trash

app/views/looks/_tabs_links.html.haml
= tabs_tag :open_tabs => { :id => "tabs", :class => "nav nav-tabs" }, :active_class => "active" do |tab|
  = tab.looks_list "My Looks", looks_path
  = tab.looks_shared "Shared Looks", shared_looks_path

app/views/looks/available_pictures.js.erb
$("#pictures-modal").html("<%= escape_javascript (render(partial: 'looks/modals/available_pictures').force_encoding("utf-8")) %>");
ReactRailsUJS.mountComponents()
$("#pictures-modal").modal('show');

app/views/looks/edit.html.haml
.breadcrumbs
  .breadcrumbs-i= link_to "Looks", looks_path
  .breadcrumbs-i Edit Look

= render 'form'

app/views/looks/extra_pictures.js.erb
$('.btn-add-picture').attr('disabled', true)
$("#pictures-modal").modal('hide');

"<% if @extra_look_pictures.present? %>"
  window.Look.addPictures("<%= j @extra_look_pictures.to_json(only: [:picture_id, :position_params], include: :picture).html_safe%>")
"<% end %>"

app/views/looks/index.html.haml
.row
  .col-md-6
    -#%h2 Looks
  .col-md-6
    = link_to new_look_path, class: "btn btn-add-new" do
      %i.glyphicon.glyphicon-plus
      Add New Look

= render "tabs_links"
= render "looks_list", is_shared_looks: is_shared_looks ||= false

app/views/looks/new.html.haml
.breadcrumbs
  .breadcrumbs-i= link_to "Looks", looks_path
  .breadcrumbs-i New Look

= render 'form'

app/views/looks/show.html.haml
.row
  .col-md-6
    %strong Name:
    = @look.name
  .col-md-6
    .btn-form-action
      = link_to looks_path, class: "" do
        %span.glyphicon.glyphicon-chevron-left
        Back to Looks
      - if @look.user_id.eql? current_user.id
        = link_to edit_look_path(@look), class: "btn btn-primary", title: 'Edit'  do
          %span.glyphicon.glyphicon-pencil
          Edit
        = link_to @look, method: :delete, class: "btn btn-sm btn-danger", data: { confirm: 'Are you sure?' } do
          %span.glyphicon.glyphicon-trash
          Delete


  - if @look.description.present?
    %strong Description:
    = @look.description
  - if @look.screen.present?
    = image_tag @look.screen.image.url, { class: "show-picture-image"}