config/routes.rb
  Rails.application.routes.draw do

  devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  ActiveAdmin.routes(self)
  root_path = 'home#index'

  get '/users/auth/:provider' => 'omniauth_sessions#create', as: 'omniauth_authorize'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    devise_scope :user do
      get 'omniauth/:provider' => 'omniauth_callbacks#localized', as: :localized_omniauth
    end

      devise_for :users, skip: :omniauth_callbacks


      get 'users/change_password'
      put 'users/save_password' => 'users#save_password'

      resources :pictures do
        get 'refresh', on: :collection
        get 'copy', on: :member
      end

      resources :looks do
         collection do
           get 'autocomplete_user_email'
           get 'shared'
         end
         member do
            post 'add_pictures'
            get 'approve_shared'
            get 'remove_shared'
         end
     end

      resources :categories do
        get 'available_pictures', on: :member
        post 'add_pictures', on: :member
      end

      resources :user_settings do
        collection do
          get 'change'
          put 'save'
        end
      end

      get 'api_keys/access_token' => 'api_keys#recreate_access_token'

      get 'users/profile', as: 'user_root'
      root to: root_path

      mount External::ApiVersion1 => '/'

      match '*path', :to => 'application#path_not_found', via: [:get, :post]
  end

end

app/views/shared/_error_message.html.haml
- if entity.errors.any?
  %section#errors
    %h4= "#{entity.errors.count} #{entity.errors.count > 1 ? "errors" : "error"} prohibited this object from being saved"
    %ul
      - entity.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_flash_message.html.haml
- if notice
  .alert.alert-success
    = notice
- if alert
  .alert.alert-danger
    = alert

app/views/shared/_header.html.haml
%header
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#lookbox-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "Lookbox", root_path, class: 'navbar-brand'
      #lookbox-navbar-collapse.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= active_link_to t("main_menu.pictures"), pictures_path, class: "btn"
            %li= active_link_to t("main_menu.categories"), categories_path, class: "btn"
            %li= active_link_to t("main_menu.looks"), looks_path, class: "btn"
            %li.dropdown
              = link_to "#", class: "dropdown-toggle btn #{active_current_page_menu(edit_user_registration_path, users_change_password_path, change_user_settings_path)}",
                'data-toggle': "dropdown", 'aria-expanded': "false", 'aria-haspopup': "true", role: 'button' do
                = t("main_menu.account")
                %span.caret
              %ul.dropdown-menu{role: "menu"}
                %li= link_to t("main_menu.my_profile"), edit_user_registration_path, class: ""
                %li= link_to t("main_menu.change_password"), users_change_password_path, class: ""
                %li= link_to t("main_menu.settings"), change_user_settings_path, class: ""
            %li= render 'shared/locale_switcher'
            %li
              = link_to destroy_user_session_path, method: :delete, data: { confirm: t("modal_forms.confirm_exit"), confirm_success_label: 'Exit' }, title: t("main_menu.log_out") do
                %span.glyphicon.glyphicon-log-out
          - else
            %li= render 'shared/locale_switcher'
            %li
              = link_to new_user_session_path, title: t("main_menu.log_in") do
                %span.glyphicon.glyphicon-log-in

app/views/shared/_locale_switcher.html.haml
%li.dropdown
  = link_to '#', class: 'dropdown-toggle language-select', 'data-toggle' => 'dropdown' do
    %i.icon-globe
    %span #{I18n.locale.to_s}
    %b.caret
  %ul.dropdown-menu#locale-link
    - Locale.list.each do |loc|
      %li
        = link_to params.merge(locale: loc.locale) do
          %span.badge #{loc.locale}
          = t(loc.locale, {locale: loc.locale})