config/routes.rb
  Rails.application.routes.draw do

  devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  ActiveAdmin.routes(self)
  root_path = 'home#index'

  get '/users/auth/:provider' => 'omniauth_sessions#create', as: 'omniauth_authorize'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    devise_scope :user do
      get 'omniauth/:provider' => 'omniauth_callbacks#localized', as: :localized_omniauth
    end

      devise_for :users, skip: :omniauth_callbacks


      get 'users/change_password'
      put 'users/save_password' => 'users#save_password'

      resources :pictures do
        get 'refresh', on: :collection
        get 'copy', on: :member
      end

      resources :looks do
         collection do
           get 'autocomplete_user_email'
           get 'shared'
         end
         member do
            post 'add_pictures'
            get 'approve_shared'
            get 'remove_shared'
         end
     end

      resources :categories do
        get 'available_pictures', on: :member
        post 'add_pictures', on: :member
      end

      resources :user_settings do
        collection do
          get 'change'
          put 'save'
        end
      end

      get 'api_keys/access_token' => 'api_keys#recreate_access_token'

      get 'users/profile', as: 'user_root'
      root to: root_path

      mount External::ApiVersion1 => '/'

      match '*path', :to => 'application#path_not_found', via: [:get, :post]
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  include CopyCarrierwaveFile
  mount_uploader :image, Rails.application.secrets.use_cloudinary ? CloudinaryUploader : ImageUploader
  crop_uploaded :image
  acts_as_paranoid

  belongs_to :user
  has_many :category_pictures
  has_many :categories, -> { uniq }, :through => :category_pictures
  has_many :look_pictures, dependent: :destroy
  has_many :looks, -> { uniq }, :through => :look_pictures

  attr_accessor :image_encoded, :image_timestamp, :direct_image_url
  serialize :transformation_params, Hash
  store_accessor :transformation_params, :rotation, :crop_x, :crop_y, :crop_w, :crop_h

  validates :title, presence: true
  validates_length_of :title, :minimum => 5, :if => proc{|p| p.title.present?}
  validates :user, presence: true
  validates_with UrlValidator, fields: [:direct_image_url, :link]

  scope :preload_categories, -> { eager_load(:categories) }
  scope :uncategorized, -> { includes(:categories).where( categories: { id: nil } ) }

  # a bit odd, but of many-to-many category and picture
  scope :available_for_category, -> (cat_id) { self.all - includes(:categories).where( categories: { id: cat_id } ) }
  #scope :available_for_look, -> (look_id) { self.all - includes(:looks).where( looks: { id: look_id } ) }

  scope :category_search, -> (include_subcat, *category_ids) do

    any_categories = proc(&:blank?)
    with_included_subcategories = proc{ include_subcat == '1' }
    category_ids_with_children = proc{ |cat_ids| cat_ids.concat(Category.where(id: cat_ids).eager_load(:children).map{|cat| cat.children}.flatten).uniq }

    category_ids.reject!(&:empty?)
    category_ids.delete('0') || category_ids.delete_at(category_ids.index('1') || category_ids.length)
    category_ids.push(nil) if category_ids.delete('-1') # for uncategorized

    case category_ids
      when any_categories
        self.eager_load(:categories)
      when with_included_subcategories
        self.eager_load(:categories).where( categories: { id: category_ids_with_children.call(category_ids) })
      else
        self.eager_load(:categories).where( categories: { id: category_ids })
    end

  end
  
  scope :include_subcategories, -> (include_subcat = nil) { }

  scope :title_description_search, -> (search_text) do
    self.ransack(title_or_description_cont_any: search_text.split).result
  end

  before_save :load_image_from_remote_url, if: ->(obj){ obj.direct_image_url.present? }
  after_update :update_picture
  after_destroy :remove_cloud_image, if: ->(obj){ Rails.application.secrets.use_cloudinary && obj.image.url.present?}

  # whitelist the scope
  def self.ransackable_scopes(auth_object = nil)
    [:category_search, :include_subcategories, :title_description_search]
  end

  def load_image_from_remote_url
    #if valid_direct_url?
      self.remote_image_url = direct_image_url.strip
      self.image = nil
    #end
  end

  def update_picture
    if Rails.application.secrets.use_cloudinary
      previous_image = self.changes.fetch(:image, {}).first
      if previous_image.try(:url) && !self.remote_image_url && !previous_image.try(:filename).eql?(self.image.try(:filename))
        remove_cloud_image(previous_image_public_id(previous_image))
      end
    else
      recreate_image if self.rotation.present?
      create_image_timetamp if self.crop_x.present?
    end
  end

  def duplicate
    Rails.application.secrets.use_cloudinary ? self.make_cloudinary_copy : self.make_carrierwave_copy
  end

  def make_carrierwave_copy
    copy = self.dup
    copy.title += ' copy'
    CopyCarrierwaveFile::CopyFileService.new(self, copy, :image).set_file
    copy.save
    copy
  end

  def make_cloudinary_copy
    copy = Picture.new(self.attributes.except(:image).merge(id: nil, title: "#{self.title} copy"))
    copy.save
    copy.remote_image_url = self.image_url # to save image path with existing picture id
    copy.save
    copy
  end

  #['link', 'direct_image_url'].each { |attribute| define_method(:"#{attribute}=") {|value| super(value.try(:strip))}  }

  def link=(value)
    super(value.try(:strip))
  end

  def possible_categories
    self.categories.map{|cat| cat.self_and_ancestors.ids}.flatten.uniq
  end

  private
  def recreate_image
    image.recreate_versions!
    #create_image_timetamp #for local image storage
  end

  def remove_cloud_image(public_id = self.image.public_id)
    Cloudinary::Uploader.destroy(public_id)
  end

  def previous_image_public_id(previous_image)
    CloudinaryUploader::CLOUD_FOLDER + previous_image.url.split(CloudinaryUploader::CLOUD_FOLDER).last.split('.').first
  end

  def create_image_timetamp
    self.image_timestamp = DateTime.now.to_i
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:google], :authentication_keys => [:login], :reset_password_keys => [ :login ], :confirmation_keys => [ :login ]

  acts_as_paranoid

  has_many :pictures
  has_many :categories
  has_many :looks

  has_many :user_looks, dependent: :destroy
  has_many :shared_looks, through: :user_looks, source: :look
  has_one :user_setting, :dependent => :destroy

  validates :name, length: {maximum: 25}, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9 \- _]*\z/, message: "invalid name format" }, if: 'name.present?'

  attr_readonly :email
  attr_accessor :login

  def current_user_setting
    user_setting || UserSetting.new(locale: Locale.default_locale, user: self)
  end

  def update_password_with_new(params)
    current_password = params.delete(:current_password)
    if valid_password?(current_password)
      update_attributes(params)
    else
      self.assign_attributes(params)
      self.valid?
      self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
      false
    end
  end

  def potential_shared_users
    User.where.not(id: self.id).to_json(only: [:id, :email, :name])
  end

  def self.from_omniauth(auth)
    user = self.find_by_email(auth.info.email)
    if user
      user.uid, user.provider = auth.uid, auth.provider
      user.save if user.changed?
    else
      user_password = SecureRandom.urlsafe_base64(6)
      user = self.create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.name = auth.info.name
        user.password = user_password
        user.skip_confirmation!
      end
      UserMailer.google_user_site_password(user, user_password).deliver_now if user.persisted?
    end
    user
  end

  def self.find_user_by_access_token(access_token)
    User.eager_load(:user_setting => :api_key).where("api_keys.access_token = ? and api_keys.active = ?", access_token, true).first
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["name = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :set_look_pictures_search, only: :index, if: proc{ params[:look_id].present? }
  protect_from_forgery except: :index
  #respond_to :html, :js

  include SearchFilter

  # GET /pictures
  def index
    @search, @pictures = filtered_pictures(current_user.pictures, params)
    respond_to do |format|
      format.html 
      format.js do
        @available_pictures = @pictures
        search_view = if params[:look_id] then 'looks/available_pictures' elsif params[:category_id] then 'categories/available_pictures' else {js: 'No results was found'}  end
        render search_view
      end
    end
  end

  # GET /pictures/1
  def show
    #if stale?(last_modified: @picture.updated_at.utc, etag: @picture.cache_key)
      respond_to do |format|
        format.html
        format.js
      end
    #end
  end

  # GET /pictures/new
  def new
    @picture = current_user.pictures.new.decorate
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  def create
    @picture = current_user.pictures.new(picture_params.except(:image)).decorate
    respond_to do |format|
      if @picture.save
        @picture.image = picture_params[:image] if picture_params[:image].present?
        @picture.save if @picture.changed?
        format.html { redirect_to pictures_path, notice: success_action_notice('created') }
        format.js { render :create }
      else
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /pictures/1
  def update
    respond_to do |format|
      if @picture.update(picture_params) #update_attributes
        format.html { redirect_to pictures_path, notice: success_action_notice('updated') }
        format.js { render :update, locals: {notice: success_action_notice('updated')} }
      else
        format.html { render :edit }
        format.js { render :edit }
      end
    end
  end

  # DELETE /pictures/1
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: success_action_notice('destroyed') }
    end
  end

  def refresh
    respond_to do |format|
      format.html do
        session.delete(:pictures_filter)
        redirect_to pictures_path
      end
      format.js do
        session.delete :look_pictures_search
        redirect_to pictures_path(look_id: params[:look_id])
      end
    end
  end

  def copy
    @picture = current_user.pictures.find(params[:id]).duplicate
    respond_to do |format|
      format.html { render :index, notice: success_action_notice('copied')}
      format.js { render :copy, locals: {notice: success_action_notice('copied')} }
    end
  end

  private
    def success_action_notice(action)
      "Picture was successfully #{action}."
    end

    def set_picture
      @picture = current_user.pictures.find(params[:id]).decorate
    end

    def set_look_pictures_search
      session[:look_pictures_search] = { page:  params[:page], q: params[:q]} if params[:page]
      params.deep_merge!(session[:look_pictures_search]) if params[:restore_page].present? && session[:look_pictures_search]
    end

    def paginate_pictures(pictures, per_page)
      Kaminari.paginate_array(PictureDecorator.wrap(pictures)).page(params[:page]).per(per_page)
    end

    def picture_params
      params.require(:picture).transform_keys{|k| k.sub('image_crop', 'crop')}.permit(:crop_x, :crop_y, :crop_w, :crop_h, :title, :description, :rotation, :user_id, :image, :direct_image_url, :link, category_ids: [])
    end

end

app/helpers/pictures_helper.rb
module PicturesHelper
  def original_image_rotation(rotation)
    Rails.application.secrets.use_cloudinary && rotation ? rotation : 0
  end

  def selected_categories_for_multiselect
    categories = params.dig(:q, :category_search)
    categories.flatten.delete_if{|cat| cat.blank? || cat == '0'} if categories
  end

end

app/views/pictures/_btns_modal_footer.html.haml
= link_to 'Back to Show', picture_path(picture),  { class: "btn btn-primary", remote: true }
= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?', remote: true }

app/views/pictures/_form.html.haml
= form_for(@picture, remote: is_remote ||= false,authenticity_token: true, html: { multipart: true}) do |f|

  %div{class: "#{is_remote ? 'modal-body' : '' }"}

    .picture-form-block

      = render 'shared/error_message', entity: @picture

      .form-group
        .row
          = f.label :title, 'Title*', class: "col-sm-2 control-label"
          .col-sm-10
            .title-input-wrapper
              = f.text_field :title, class: 'form-control'
              %span.clear-input-btn
                &times;
      .form-group
        .row
          = f.label :description, class: "col-sm-2 control-label"
          .col-sm-10
            = f.text_area :description, class: 'form-control'

      .form-group
        .row
          = f.label :link, class: "col-sm-2 control-label"
          .col-sm-10.title-input-wrapper
            = f.text_field :link, class: 'form-control'
            %span.clear-input-btn
              &times;

      .form-group
        .row
          = f.label t('pictures.category'), class: "col-sm-2 control-label"
          .col-sm-10
            = select :picture, :category_ids, nested_set_options(current_user.categories){|cat|  "#{'-' * cat.depth} #{cat.name}" }, { include_blank: true }, { multiple: true, class: "select2-select"}
      .form-group
        .row
          = f.label :image, class: "col-sm-2 control-label"
          .col-sm-6.title-input-wrapper
            = f.text_field :direct_image_url, class: 'form-control'
            %span.clear-input-btn
              &times;
          .col-sm-4
            %i.glyphicon.glyphicon-info-sign.infopopover{'data-content' => 'Insert direct image url from other resource or upload image from your device'}
      .form-group
        .row
          .image-uploader{:'data-provides' => "fileinput", class: "fileinput fileinput-#{@picture.image.present? ? 'exists' : 'new'}"}
            .col-sm-4.col-sm-offset-2
              .file-image-preview
                .fileinput-preview.thumbnail{:'data-trigger' => 'fileinput'}
                  = image_tag @picture.preview_image_large, class: "image-space"
              .crop-image-preview
                .crop-previewbox.thumbnail
                  = f.previewbox :image
            .col-sm-6
              .btn.btn-default.btn-file
                %span.fileinput-new{title: 'Load'}
                  %i.glyphicon.glyphicon-picture
                %span.fileinput-exists{title: 'Reload'}
                  %i.glyphicon.glyphicon-picture
                %input{type: 'file', name: 'picture[image]', id: 'file-input'}
              .btn.btn-default.btn-file.fileinput-exists.image-crop
                %i.glyphicon.glyphicon-scissors{title: 'Crop'}
              .btn.btn-default.fileinput-exists{id: 'rotate_image', title: 'Rotate'}
                %i.glyphicon.glyphicon-repeat
                = f.hidden_field :rotation, value: original_image_rotation(@picture.rotation)
                = hidden_field_tag 'original_picture_rotation', original_image_rotation(@picture.rotation)
                = hidden_field_tag 'current_picture_rotation', 0
              .btn.btn-default.btn-file.fileinput-new.image-refresh{title: 'Refresh'}
                %i.glyphicon.glyphicon-refresh
              .btn.btn-default.btn-file.fileinput-exists.image-refresh{title: 'Refresh'}
                %i.glyphicon.glyphicon-refresh
              .btn.btn-default.fileinput-exists.image-delete{:'data-dismiss' => 'fileinput', title: 'Delete'}
                %i.glyphicon.glyphicon-remove

    .crop-image-block
      .form-group
        .row
          .col-sm-2.col-sm-offset-8
            .image-crop.ok
              %span.btn.btn-default.btn-file
                %i.glyphicon.glyphicon-scissors
                Crop Image
          .col-sm-2
            .image-crop.cancel
              %span.btn.btn-default.btn-file
                Cancel
      .form-group
        .row
          = f.cropbox :image

  %div{class: "#{is_remote ? 'modal-footer':''}"}
    .form-group
      .row
        .col-sm-offset-2.col-sm-10
          .actions
            - if @picture.persisted? && is_remote
              %span{data: {toggle: 'modal', target: '#picture-modal-form'}, class: 'back-to-show'}
                = link_to '#', data: {toggle: 'modal', target: '#picture-modal-show', picture: @picture}, class: "btn-back-pictures" do
                  %span.glyphicon.glyphicon-chevron-left
                  = t('modal_forms.back_to_show')
            = f.submit t('modal_forms.save'), class: 'btn btn-primary', data: {disable_with: 'Saving...' }

:javascript
  $('.select2-select').select2({
    theme: "bootstrap"
  });
  document.getElementById('file-input').onchange = function (e) { window.LoadImageWithOrientation(e.target.files[0]) }

app/views/pictures/_form_modal.html.haml
%div{class: "modal fade", id: "modal-form", tabindex: "-1", role: "dialog", "aria-labelledby": "modal-label "}
  %div{class: "modal-dialog", role: "document"}
    .modal-content
      .modal-header
        = button_to 'Close', {}, {class: "close", "data-dismiss": "modal"}
        %h4.modal-title#modal-label
      .modal-body

      .modal-footer

app/views/pictures/_index.html.haml
- @pictures.each do |picture|
  - next if picture.image.url.nil?
  .picture-block
    %div{class: "modal fade", id: "picture-modal-#{picture.id}", tabindex: "-1", role: "dialog", "aria-labelledby": "modal-label "}
      = render 'pictures/modals/show', picture: picture
    = image_tag picture.image.thumb, class: "image-space"
    %br
    .picture-action
      = link_to 'Show', "#", data: {class: "btn btn-primary btn-lg", toggle: "modal", target: "#picture-modal-#{picture.id}"}
      = link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' }

  = paginate @pictures #, remote: true

app/views/pictures/_search_filters.html.haml
%label= t("search_filters.sort_by")
- is_remote = defined?(@available_pictures) ? true : false
= sort_link @search, :title, t("search_filters.title"), {}, { remote: is_remote, class: '' }
= sort_link @search, :created_at, t("search_filters.date"), {}, { remote: is_remote, class: '' }
.form-group
  .title-input-wrapper
    -#= f.text_field :title_or_description_cont_any, class: "search-query form-control", "placeholder" => t("search_filters.type_title_or_part")
    = f.text_field :title_description_search, class: "search-query form-control", "placeholder" => t("search_filters.type_title_or_part")
    %span.clear-input-btn
      &times;
.form-group.search-filters-category
  %label.search-label= t("search_filters.category")
  = f.select :category_search, nested_set_options(current_user.categories) {|cat| "#{'-' * cat.depth} #{cat.name}" }.insert(0,  ['Uncategorized', '-1']), { include_blank: t("search_filters.include_blank_all") },  { multiple: true, class: "select2-select hidden" }
  -#= f.select :category_search, categories_with_depth_name(current_user.categories).insert(0,  ['Uncategorized', '-1']), { include_blank: t("search_filters.include_blank_all")}, onChange: "$(this.form).submit()", class: 'form-control'
  = f.check_box :include_subcategories, onChange: "$(this.form).submit()"
  = t("search_filters.include_subcategories")
= f.submit 'Search', :class => "btn btn-grey"
- if @pictures.any?
  %label.search-label= "Found: #{@pictures.total_count}"
= link_to refresh_pictures_path(look_id: look_id_for_pictures_search), {remote: is_remote, class: "btn" } do
  = t("search_filters.refresh")
  %i.glyphicon.glyphicon-refresh
= react_component 'CategoriesSelect', { selected_categories: selected_categories_for_multiselect().to_json }

app/views/pictures/_show_modal.html.haml
%div{class: "modal-dialog", role: "document"}
  .modal-content
    .modal-header
      = button_to 'Close', {}, {class: "close", "data-dismiss": "modal"}
      %h4.modal-title#modal-label= picture.title
    .modal-body
      = picture.description
      = image_tag picture.image.url
    .modal-footer
      = link_to 'Edit', edit_picture_path(picture),  {class: "btn btn-primary", remote: true}
      = link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' }

app/views/pictures/copy.js.erb
window.Picture.addPicture("<%= j @picture.to_json(include: :image).html_safe%>")
$("#picture-modal-form").modal('hide');
window.FlashMessage.show("<%= escape_javascript (render(partial: 'shared/flash_message', locals: {notice: notice}).force_encoding("utf-8")) %>")

app/views/pictures/edit.html.haml
.row
  .col-md-6
    %h2= t("pictures.edit_picture")
  .col-md-6
    .btn-form-action
      = link_to pictures_path, class: "btn" do
        %span.glyphicon.glyphicon-chevron-left
        = t("pictures.back_to_pictures")
      = link_to @picture, class: "btn btn-primary", title: 'Show' do
        %span.glyphicon.glyphicon-loop
        = t("modal_forms.show")

= render 'form'

app/views/pictures/edit.js.erb
$("#picture-modal-form").html("<%= escape_javascript (render('pictures/modals/form').force_encoding("utf-8")) %>");
$("#modal-label").html("<%= t('pictures.edit_picture')%>");
$("#picture-modal-form").modal('show');
$("input[id^='picturedecorator_image_crop']").prop('disabled', true)
if ("<%= @picture.id.to_s%>" != $('#picture-modal-show .modal-content').attr('data-picture-id')){
  $('.back-to-show').hide()
}

app/views/pictures/index.html.haml
.pictures
  .row
    .col-md-6
      %h2= t('pictures.pictures')
    .col-md-6
      = link_to new_picture_path, remote: true, class: "btn btn-add-new" do
        %i.glyphicon.glyphicon-plus
        New Picture

  .row
    .filters
      = search_form_for @search, enforce_utf8: false, html: {class: "form-inline" } do |f|
        = render 'search_filters', f: f
    - unless @pictures.any?
      = current_user.pictures.any? ? t("search_filters.no_results") : t("search_filters.no_items", {item: t('pictures.picture'), button_name: t("pictures.new_picture")})


  .row
    #pictures-container.pictures-list
      = react_component 'Pictures', { pictures: @pictures.to_json(include: {image: {}, categories: {only: [:id, :name]}}) }
      = paginate @pictures #, remote: true

  %div{class: "modal fade", id: "picture-modal-form", tabindex: "-1", role: "dialog", :"aria-labelledby" => "modal-label "}

  -#= cl_image_tag(Picture.last.image, :transformation=>[{angle: 90, width: 100, height: 100, gravity: "north", page: 2, :effect=>"saturation:100", crop: "fill"}, {:effect=>"sharpen"}])

app/views/pictures/new.html.haml
%h2= t("pictures.add_new_picture")

= render 'form'

= link_to pictures_path class: "btn" do
  %span.glyphicon.glyphicon-chevron-left
  = t("pictures.back_to_pictures")

app/views/pictures/new.js.erb
$("#picture-modal-form").html("<%= escape_javascript (render('pictures/modals/form').force_encoding("utf-8")) %>");
$("#modal-label").html("<%= t("pictures.add_new_picture")%>");
$("#picture-modal-form").modal('show');

app/views/pictures/show.html.haml
.row
  .col-md-6
    %strong Title:
    = @picture.title
  .col-md-6
    .btn-form-action
      = link_to edit_picture_path(@picture), class: "btn" do
        %span.glyphicon.glyphicon-chevron-left
        = t("pictures.back_to_pictures")
      = link_to edit_picture_path(@picture), class: "btn btn-primary", title: 'Edit' do
        %span.glyphicon.glyphicon-pencil
        = t("modal_forms.edit")

- if !@picture.description.present?
  .row
    %strong= Picture.human_attribute_name("description")
    = @picture.description
.row
  = image_tag @picture.preview_image_large, class: 'picture-show'

app/views/pictures/update.js.erb
$("#picture-modal-form").modal('hide');
window.Picture.updatePicture("<%= j @picture.to_json(include: :image, methods: [:image_timestamp, :possible_categories]).html_safe%>")
window.FlashMessage.show("<%= escape_javascript (render(partial: 'shared/flash_message', locals: {notice: notice}).force_encoding("utf-8")) %>")