config/routes.rb
  Rails.application.routes.draw do

  devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  ActiveAdmin.routes(self)
  root_path = 'home#index'

  get '/users/auth/:provider' => 'omniauth_sessions#create', as: 'omniauth_authorize'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    devise_scope :user do
      get 'omniauth/:provider' => 'omniauth_callbacks#localized', as: :localized_omniauth
    end

      devise_for :users, skip: :omniauth_callbacks


      get 'users/change_password'
      put 'users/save_password' => 'users#save_password'

      resources :pictures do
        get 'refresh', on: :collection
        get 'copy', on: :member
      end

      resources :looks do
         collection do
           get 'autocomplete_user_email'
           get 'shared'
         end
         member do
            post 'add_pictures'
            get 'approve_shared'
            get 'remove_shared'
         end
     end

      resources :categories do
        get 'available_pictures', on: :member
        post 'add_pictures', on: :member
      end

      resources :user_settings do
        collection do
          get 'change'
          put 'save'
        end
      end

      get 'api_keys/access_token' => 'api_keys#recreate_access_token'

      get 'users/profile', as: 'user_root'
      root to: root_path

      mount External::ApiVersion1 => '/'

      match '*path', :to => 'application#path_not_found', via: [:get, :post]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  include TheSortableTree::Scopes
  acts_as_nested_set

  belongs_to :user
  has_many :category_pictures
  has_many :pictures, -> { uniq }, :through => :category_pictures

  alias_attribute :title, :name
  accepts_nested_attributes_for :category_pictures
  accepts_nested_attributes_for :pictures

  validates :name, presence: true
  validates_length_of :name, :minimum => 3, :if => proc{|p| p.name.present?}
  validates :user_id, presence: true


  scope :main, -> { where(parent: nil)}
  scope :name_order, -> { reorder('name DESC') }
  scope :created_order, -> { reorder('created_at, name') }

  before_save do |cat|
   cat.user = cat.parent.user if cat.parent.present?
  end

  def move_subcategories
    self.children.each do |cat_child|
      if cat_child.depth > 1
        cat_child.move_to_child_of(cat_child.parent.parent)
      else
        cat_child.move_to_root
      end
    end
    self.reload
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy, :available_pictures, :add_pictures]

  def index
    @search = current_user.categories.eager_load(:pictures).nested_set.search(params[:q])
    @categories = @search.result #.select('id, name, description, parent_id, depth').all
  end

  def new
    @category = current_user.categories.new(parent_id: params[:parent_id]).decorate
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @category = current_user.categories.new(category_params).decorate
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @category.move_subcategories unless params[:delete_with_sub].present?
    @category.destroy
    #MoveSubcategoriesJob.set(wait: 1.minute).perform_later(@category.id) unless params[:delete_with_sub].present?
    redirect_to categories_path, notice: 'Category was successfully destroyed.'
  end

  def available_pictures
    @available_pictures = current_user.pictures.available_for_category(params[:id])
  end

  def add_pictures
    @category.pictures << current_user.pictures.where("id in (?)", category_params[:picture_ids])
  end

  private

  def set_category
    @category = current_user.categories.find(params[:id]).decorate
  end

  def category_params
    params.require(:category).permit(:name, :description, :user_id, :parent_id, picture_ids: [])
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper

end

app/views/categories/_form.html.haml
= form_for(@category, authenticity_token: true, remote: is_remote || false, :html => {:multipart => true}) do |f|
  = render 'shared/error_message', entity: @category

  .form-group
    .row
      = f.label :name, class: "col-sm-2 control-label"
      .col-sm-10
        = f.text_field :name

  .form-group
    .row
      = f.label :description, class: "col-sm-2 control-label"
      .col-sm-10
        = f.text_area :description

  .form-group
    .row
      = f.label :parent_id, class: "col-sm-2 control-label"
      .col-sm-10
        -#= f.select :parent_id, nested_options(@category.available_categories_as_parent, selected: @category.parent) {|cat| "#{'-' * cat.depth} #{cat.name}" }, { include_blank: true }, { class: "nested_options" }
        = f.select :parent_id, nested_set_options(@category.available_categories_as_parent) {|cat|  "#{'-' * cat.depth} #{cat.name}" }, { include_blank: true }

  .form-group
    .row
      .col-sm-offset-2.col-sm-10
        .actions
          = f.submit 'Save', class: 'btn btn-primary'

  = render 'pictures_list', pictures: @category.pictures

app/views/categories/_pictures_list.html.haml
- pictures.each do |picture|
  .picture-block
    = check_box_tag :picture_ids, picture.id, true, name: 'category[picture_ids][]', class: "mark-picture-chbox"
    .image-block
      = image_tag picture.image.thumb, class: "image-space", 'data-toggle': "tooltip", title: "Click to select/diselect"
    .picture-action
      .select-diselect-picture
        .remove-picture
          %i.glyphicon.glyphicon-remove
        .refresh-picture{style: "display: none"}
          %i.glyphicon.glyphicon-refresh

app/views/categories/_show.html.haml
- if @category.description.present?
  .row
    %strong Description:
    = @category.description

- if @category.parent.present?
  .row
    %strong Parent category:
    = link_to @category.parent.name, category_path(@category.parent), remote: true

- if @category.descendants.any?
  .row
    #category-descendants
      %strong Subcategories count:
      = @category.descendants.count

.row
  %strong Created:
  = @category.created_at
.row
  %strong Last Modified:
  = @category.updated_at

app/views/categories/add_pictures.js.erb
$("#category_<%= @category.id%>_pictures_count").html("<%= @category.pictures.count %>");
$("#pictures-modal").modal('hide');

app/views/categories/available_pictures.js.erb
$("#pictures-modal").html("<%= escape_javascript (render 'categories/modals/available_pictures') %>");
ReactRailsUJS.mountComponents()
$("#pictures-modal").modal('show');

app/views/categories/edit.html.haml
%h2 Edit Category

= render 'form'

= link_to 'Show', @category
= link_to 'Back to Categories', categories_path

app/views/categories/edit.js.erb
$("#modal-form").html("<%= escape_javascript (render('categories/modals/form').force_encoding("utf-8")) %>");
$("#modal-label").html("Edit Category");
$("#modal-form").modal('show');

app/views/categories/index.html.haml
.row
  .col-md-6
    %h2 Categories

.row
  .col-md-6
    - if @search.result.any?
      .filters
        = search_form_for @search, enforce_utf8: false, html: { class: "form-inline" } do |f|
          %label Sort:
          = sort_link @search, :name, 'name', {}, { class: '' }
          = sort_link @search, :created_at, 'date', {}, { class: '' }
      .categories-expansion
        = link_to 'expand', '#', class: 'category-expand-all'
        = "/"
        = link_to 'hide', '#', class: 'category-hide-all'
        all
    - else
      No one category has been added yet. Press 'New category' button to add the first one.

  .col-md-6
    = link_to new_category_path, remote: true, class: "btn btn-add-new" do
      %i.glyphicon.glyphicon-plus
      New Category

%ol.sortable_tree{  data: { rebuild_url: categories_path } }
  = sortable_tree(@categories, {type: :sortable, id: "categories-set"})

#pictures-modal.modal.fade{ tabindex: "-1", role: "dialog", "aria-labelledby": "modal-label "}

.category-row
  %div{class: "modal fade", id: "modal-form", tabindex: "-1", role: "dialog", "aria-labelledby": "modal-label "}

:javascript
  if ($(ConstantsList.FlashNotice.messageClass).children().length > 0){
    $(ConstantsList.FlashNotice.messageClass).fadeOut(ConstantsList.FlashNotice.fadeOutTime)
  }

app/views/categories/new.html.haml
%h2 Add new category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/new.js.erb
$("#modal-form").html("<%= escape_javascript (render('categories/modals/form').force_encoding("utf-8")) %>");
$("#modal-form .modal-footer").html("");
$("#modal-label").html("Add New Category");
$("#modal-form").modal('show');

app/views/categories/show.html.haml
%p
  .row
    %strong Name:
    = @category.name
  = render 'show'

= link_to 'Edit', edit_category_path(@category)
= link_to 'Categories', categories_path

app/views/categories/show.js.erb
$("#modal-form").html("<%= escape_javascript (render(partial: 'categories/modals/show', :locals => { category: @category } ).force_encoding("utf-8")) %>");
$("#modal-form").modal('show');